[build]
  command = "npx prisma generate && SKIP_TYPE_CHECK=true npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "your-database-url-here"